// Array of images for each team, no available API
var teamPics = [
    {team: "Boston Celtics" ,
    imgUrl: "./assets/1280px-Boston_Celtics.svg.png"},
    {team: "Brooklyn Nets" ,
    imgUrl: "./assets/1024px-Brooklyn_Nets_newlogo.svg.png"},
    {team: "New York Knicks" ,
    imgUrl: "./assets/1920px-New_York_Knicks_logo.svg.png"},
    {team: "Philadelphia 76ers" ,
    imgUrl: "./assets/1280px-Philadelphia_76ers_logo.svg.png"},
    {team: "Toronto Raptors" ,
    imgUrl: "./assets/1280px-Toronto_Raptors_logo.svg.png"},
    {team: "Chicago Bulls" ,
    imgUrl: "./assets/1280px-Chicago_Bulls_logo.svg.png"},
    {team: "Cleveland Cavaliers" ,
    imgUrl: "./assets/800px-Cleveland_Cavaliers_logo.svg.png"},
    {team: "Detroit Pistons" ,
    imgUrl: "./assets/1280px-Pistons_logo17.svg.png"},
    {team: "Indiana Pacers" ,
    imgUrl: "./assets/1280px-Indiana_Pacers.svg.png"},
    {team: "Milwaukee Bucks" ,
    imgUrl: "./assets/1024px-Milwaukee_Bucks_logo.svg.png"},
    {team: "Atlanta Hawks" ,
    imgUrl: "./assets/1280px-Atlanta_Hawks_logo.svg.png"},
    {team: "Charlotte Hornets" ,
    imgUrl: "./assets/1280px-Charlotte_Hornets_(2014).svg.png"},
    {team: "Miami Heat" ,
    imgUrl: "./assets/1024px-Miami_Heat_logo.svg.png"},
    {team: "Orlando Magic" ,
    imgUrl: "./assets/1920px-Orlando_Magic_logo.svg.png"},
    {team: "Washington Wizards" ,
    imgUrl: "./assets/1280px-Washington_Wizards_logo.svg.png"},
    {team: "Denver Nuggets" ,
    imgUrl: "./assets/1280px-Denver_Nuggets.svg.png"},
    {team: "Minnesota Timberwolves" ,
    imgUrl: "./assets/1280px-Minnesota_Timberwolves_logo.svg.png"},
    {team: "Oklahoma City Thunder" ,
    imgUrl: "./assets/1280px-Oklahoma_City_Thunder.svg.png"},
    {team: "Portland Trail Blazers" ,
    imgUrl: "./assets/1920px-Portland_Trail_Blazers_logo.svg.png"},
    {team: "Utah Jazz" ,
    imgUrl: "./assets/2560px-Utah_Jazz_logo_(2016).svg.png"},
    {team: "Golden State Warriors" ,
    imgUrl: "./assets/1024px-Golden_State_Warriors_logo.svg.png"},
    {team: "Los Angeles Clippers" ,
    imgUrl: "./assets/1920px-Los_Angeles_Clippers_(2015).svg.png"},
    {team: "Los Angeles Lakers" ,
    imgUrl: "./assets/1920px-Los_Angeles_Lakers_logo.svg.png"},
    {team: "Phoenix Suns" ,
    imgUrl: "./assets/1280px-Phoenix_Suns_logo.svg.png"},
    {team: "Sacramento Kings" ,
    imgUrl: "./assets/1024px-SacramentoKings.svg.png"},
    {team: "Dallas Mavericks" ,
    imgUrl: "./assets/1280px-Dallas_Mavericks_logo.svg.png"},
    {team: "Houston Rockets" ,
    imgUrl: "./assets/1024px-Houston_Rockets.svg.png"},
    {team: "Memphis Grizzlies" ,
    imgUrl: "./assets/1024px-Memphis_Grizzlies.svg.png"},
    {team: "New Orleans Pelicans" ,
    imgUrl: "./assets/1920px-New_Orleans_Pelicans_logo.svg.png"},
    {team: "San Antonio Spurs" ,
    imgUrl: "./assets/san_antonio_spurs.png"},
    {team: "Baltimore Orioles" ,
    imgUrl: "./assets/1920px-Baltimore_Orioles_cap.svg.png"},
    {team: "Boston Red Sox" ,
    imgUrl: "./assets/1280px-RedSoxPrimary_HangingSocks.svg.png"},
    {team: "New York Yankees" ,
    imgUrl: "./assets/1024px-NewYorkYankees_PrimaryLogo.svg.png"},
    {team: "Tampa Bay Rays" ,
    imgUrl: "./assets/2560px-Tampa_Bay_Rays.svg.png"},
    {team: "Toronto Blue Jays" ,
    imgUrl: "./assets/1920px-Toronto_Blue_Jays_cap.svg.png"},
    {team: "Chicago White Sox" ,
    imgUrl: "./assets/1024px-Chicago_White_Sox.svg.png"},
    {team: "Cleveland Indians" ,
    imgUrl: "./assets/1024px-Cleveland_Indians_primary_logo.svg.png"},
    {team: "Detroit Tigers" ,
    imgUrl: "./assets/800px-Detroit_Tigers_logo.svg.png"},
    {team: "Kansas City Royals" ,
    imgUrl: "./assets/1024px-Kansas_City_Royals.svg.png"},
    {team: "Minnesota Twins" ,
    imgUrl: "./assets/1280px-Minnesota_Twins_logo_(low_res).svg.png"},
    {team: "Houston Astros" ,
    imgUrl: "./assets/1280px-Houston-Astros-Logo.svg.png"},
    {team: "Los Angeles Angels" ,
    imgUrl: "./assets/1024px-Los_Angeles_Angels_of_Anaheim.svg.png"},
    {team: "Oakland Athletics" ,
    imgUrl: "./assets/1280px-Oakland_A's_logo.svg.png"},
    {team: "Seattle Mariners" ,
    imgUrl: "./assets/1280px-Seattle_Mariners_logo_(low_res).svg.png"},
    {team: "Texas Rangers" ,
    imgUrl: "./assets/1280px-Texas_Rangers.svg.png"},
    {team: "Atlanta Braves" ,
    imgUrl: "./assets/2560px-Atlanta_Braves.svg.png"},
    {team: "Miami Marlins" ,
    imgUrl: "./assets/1280px-Marlins_team_logo.svg.png"},
    {team: "New York Mets" ,
    imgUrl: "./assets/1280px-New_York_Mets.svg.png"},
    {team: "Philadelphia Phillies" ,
    imgUrl: "./assets/1280px-Philadelphia_Phillies_(2019)_logo.svg.png"},
    {team: "Washington Nationals" ,
    imgUrl: "./assets/1280px-Washington_Nationals_logo_(low_res).svg.png"},
    {team: "Chicago Cubs" ,
    imgUrl: "./assets/1280px-Chicago_Cubs_logo.svg.png"},
    {team: "Cincinnati Reds" ,
    imgUrl: "./assets/Cincinnati_Reds_Logo.svg.png"},
    {team: "Milwaukee Brewers" ,
    imgUrl: "./assets/1280px-Milwaukee_Brewers_logo.svg.png"},
    {team: "Pittsburgh Pirates" ,
    imgUrl: "./assets/800px-Pittsburgh_Pirates_logo_2014.svg.png"},
    {team: "St. Louis Cardinals" ,
    imgUrl: "./assets/1280px-St._Louis_Cardinals_logo.svg.png"},
    {team: "Arizona Diamondbacks" ,
    imgUrl: "./assets/1920px-Arizona_Diamondbacks_logo_(low_res).svg.png"},
    {team: "Colorado Rockies" ,
    imgUrl: "./assets/1024px-Colorado_Rockies_logo.svg.png"},
    {team: "Los Angeles Dodgers" ,
    imgUrl: "./assets/1280px-Los_Angeles_Dodgers_logo_(low_res).svg.png"},
    {team: "San Diego Padres" ,
    imgUrl: "./assets/1024px-SD_Logo_Brown.svg.png"},
    {team: "San Francisco Giants" ,
    imgUrl: "./assets/San_Francisco_Giants_Logo.svg.png"},
];